export const PHASES = [
  {
    id: 1, tag: "P01", label: "Capital Preservation",
    from: 100, to: 150,
    risk: 5, rr: 2, rrStr: "1:2", wr: 55, lev: "5–10×",
    note: "You start with $100 USDT on Binance Futures. Mistakes are cheap — focus on survival.",
    rules: [
      "USDT-M Perpetual contracts only on Binance Futures",
      "Maximum 2 open positions at once",
      "Stop-loss on Binance before entry — no exceptions",
      "Isolated margin — not Cross until discipline is proven",
      "After 3 consecutive losses — pause for the day",
      "Daily max drawdown: 10% of futures wallet",
    ],
  },
  {
    id: 2, tag: "P02", label: "Process Discipline",
    from: 150, to: 250,
    risk: 4, rr: 2.5, rrStr: "1:2.5", wr: 55, lev: "5–10×",
    note: "Prove P01 was not luck. Every crypto trade must be journaled.",
    rules: [
      "Journal: pair, entry, exit, SL, TP, leverage, RR, screenshot",
      "No trading during high-impact crypto news (CPI, FOMC, ETF)",
      "If daily loss exceeds 15% — session ends",
      "Check funding rate before overnight positions",
      "Weekly review in Binance Trade History",
    ],
  },
  {
    id: 3, tag: "P03", label: "Consistency",
    from: 250, to: 400,
    risk: 3.5, rr: 2.5, rrStr: "1:2.5", wr: 52, lev: "5–8×",
    note: "$250+ USDT in your futures wallet is a psychological milestone. Process > adrenaline.",
    rules: [
      "Partial close: 50% at TP1, 50% at TP2 on Binance",
      "Move SL to breakeven after TP1 (Binance trailing or manual)",
      "Do not increase leverage during a winning streak",
      "Maximum 3 trades per day",
      "Always keep liquidation price visible on screen",
    ],
  },
  {
    id: 4, tag: "P04", label: "Capital Accumulation",
    from: 400, to: 650,
    risk: 3, rr: 3, rrStr: "1:3", wr: 50, lev: "3–5×",
    note: "Steady USDT balance growth. FOMO during altseason destroys progress.",
    rules: [
      "A+ setups only on BTC/ETH majors + 1–2 alt positions",
      "Maximum 5× leverage on Binance Futures",
      "No trading when tired or after major market liquidations",
      "Document every new wallet ATH",
      "Monthly max drawdown: 15%",
    ],
  },
  {
    id: 5, tag: "P05", label: "Institutional Mindset",
    from: 650, to: 1_000,
    risk: 2.5, rr: 3, rrStr: "1:3", wr: 50, lev: "3–5×",
    note: "$650+ USDT is a threshold. Think like a portfolio manager, not a degen trader.",
    rules: [
      "Max drawdown 20% of futures wallet",
      "Diversify: BTC + ETH + max 1 alt (uncorrelated)",
      "Check BTC dominance before alt longs",
      "Fewer trades, higher confluence",
      "Move part of profits to Spot wallet (profit securing)",
    ],
  },
  {
    id: 6, tag: "P06", label: "Scaling",
    from: 1_000, to: 1_600,
    risk: 2, rr: 3, rrStr: "1:3", wr: 50, lev: "2–3×",
    note: "A mistake at this level costs tens of USDT. Position size is critical.",
    rules: [
      "Trading plan before each session (pairs, bias, max loss)",
      "Limit orders for entries — less market chasing",
      "Maximum 3× leverage",
      "After 10% monthly drawdown — reduce position size 50%",
      "Monthly win rate audit by setup",
    ],
  },
  {
    id: 7, tag: "P07", label: "Professional",
    from: 1_600, to: 2_500,
    risk: 1.5, rr: 3.5, rrStr: "1:3.5", wr: 48, lev: "2–3×",
    note: "Capital matters now. Protection > aggressive leverage.",
    rules: [
      "Hedge with BTC short when alt-heavy in risk-off",
      "Split: active Futures capital + Spot reserve",
      "Accountability partner in the group",
      "Maximum 3× leverage",
      "Track open interest and liquidation clusters",
    ],
  },
  {
    id: 8, tag: "P08", label: "Elite",
    from: 2_500, to: 4_000,
    risk: 1.5, rr: 3.5, rrStr: "1:3.5", wr: 48, lev: "1–2×",
    note: "Think in monthly USDT return %, not '10× moonshots'.",
    rules: [
      "Position sizing via Kelly (conservative fraction)",
      "Correlation risk between BTC, ETH, and alts",
      "Maximum 2× leverage",
      "TWAP for positions above $500 notional",
      "Backtest setups on historical crypto data",
    ],
  },
  {
    id: 9, tag: "P09", label: "Advanced",
    from: 4_000, to: 6_500,
    risk: 1, rr: 4, rrStr: "1:4", wr: 45, lev: "1–2×",
    note: "Large positions affect slippage. Liquidity is a real risk.",
    rules: [
      "TWAP/VWAP entries on Binance for larger orders",
      "Monitor order book depth and liquidation heatmap",
      "Do not trade illiquid alts with large size",
      "1% risk = $40+ per trade — triple-check",
      "Keep part of capital off exchange (cold storage)",
    ],
  },
  {
    id: 10, tag: "P10", label: "Target",
    from: 6_500, to: 10_000,
    risk: 0.75, rr: 4, rrStr: "1:4", wr: 45, lev: "1×",
    note: "$6.5K+ USDT. No degen leverage. Final sprint to $10K.",
    rules: [
      "Maximum 1–2× leverage or Spot only",
      "0.75% risk = $50+ per trade",
      "Highest-conviction BTC/ETH setups only",
      "Significant portion in cold wallet (not on exchange)",
      "Allocation plan after reaching $10K USDT",
    ],
  },
];
